openapi: 3.0.0
info:
  title: Bill Payment API
  description: API for paying bills online through various payment providers and services.
  version: 1.0.0
paths:
  /pay-bill:
    post:
      summary: Pay a Bill
      description: Process a bill payment for a specified amount to a designated biller.
      operationId: payBill
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayBillRequest'
      responses:
        '200':
          description: Successful bill payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayBillResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /get-bill-status:
    post:
      summary: Check Bill Payment Status
      description: Retrieve the current status of a bill payment transaction.
      operationId: getBillStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetBillStatusRequest'
      responses:
        '200':
          description: Successful status retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillStatusResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /schedule-payment:
    post:
      summary: Schedule Future Payment
      description: Schedule a bill payment for a future date.
      operationId: schedulePayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchedulePaymentRequest'
      responses:
        '200':
          description: Successful payment scheduling
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulePaymentResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    PayBillRequest:
      type: object
      properties:
        billerId:
          type: string
        accountNumber:
          type: string
        amount:
          type: number
          minimum: 0
        dueDate:
          type: string
          format: date
        paymentMethod:
          type: string
          enum: [bank_account, debit_card, credit_card]
      required:
        - billerId
        - accountNumber
        - amount
    PayBillResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
          enum: [success, pending, failed]
        confirmationNumber:
          type: string
        processingDate:
          type: string
          format: date-time
      required:
        - transactionId
        - status
    GetBillStatusRequest:
      type: object
      properties:
        transactionId:
          type: string
      required:
        - transactionId
    GetBillStatusResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
        processingDate:
          type: string
          format: date-time
        completionDate:
          type: string
          format: date-time
      required:
        - transactionId
        - status
    SchedulePaymentRequest:
      type: object
      properties:
        billerId:
          type: string
        accountNumber:
          type: string
        amount:
          type: number
          minimum: 0
        scheduledDate:
          type: string
          format: date
        paymentMethod:
          type: string
      required:
        - billerId
        - accountNumber
        - amount
        - scheduledDate
    SchedulePaymentResponse:
      type: object
      properties:
        scheduleId:
          type: string
        status:
          type: string
        scheduledDate:
          type: string
          format: date
      required:
        - scheduleId
        - status