openapi: 3.0.0
info:
  title: Get Account Balances API
  description: API for retrieving current balances for one or more bank accounts associated with a user.
  version: 1.0.0
paths:
  /get-balance:
    post:
      summary: Get Balance
      description: Retrieves the current balance for specified accounts
      operationId: getBalance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetBalanceRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBalanceResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    GetBalanceRequest:
      type: object
      properties:
        accountIds:
          type: array
          items:
            type: string
          description: List of account IDs to get balances for
      required:
        - accountIds
    GetBalanceResponse:
      type: object
      properties:
        balances:
          type: array
          items:
            type: object
            properties:
              accountId:
                type: string
              currentBalance:
                type: number
              availableBalance:
                type: number
              currency:
                type: string
              lastUpdated:
                type: string
                format: date-time
            required:
              - accountId
              - currentBalance
              - availableBalance
              - currency
              - lastUpdated