openapi: 3.0.0
info:
  title: Transaction History View API
  description: API for viewing financial transaction history across bank accounts, including details of deposits, withdrawals, and other financial activities.
  version: 1.0.0
paths:
  /get-transactions:
    post:
      summary: Get Transaction History
      description: Retrieves a list of transactions for a specified account within a date range
      operationId: getTransactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTransactionsRequest'
      responses:
        '200':
          description: Successful transaction history retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactionsResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /get-transaction-details:
    post:
      summary: Get Transaction Details
      description: Retrieves detailed information for a specific transaction
      operationId: getTransactionDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTransactionDetailsRequest'
      responses:
        '200':
          description: Successful transaction details retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactionDetailsResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    GetTransactionsRequest:
      type: object
      properties:
        accountId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        page:
          type: integer
          minimum: 1
        pageSize:
          type: integer
          minimum: 1
          maximum: 100
      required:
        - accountId
        - startDate
        - endDate
    GetTransactionsResponse:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - transactions
        - pagination
    GetTransactionDetailsRequest:
      type: object
      properties:
        transactionId:
          type: string
      required:
        - transactionId
    GetTransactionDetailsResponse:
      $ref: '#/components/schemas/TransactionDetails'
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        amount:
          type: number
        type:
          type: string
          enum: [credit, debit]
        balance:
          type: number
        category:
          type: string
      required:
        - id
        - date
        - description
        - amount
        - type
        - balance
    TransactionDetails:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        amount:
          type: number
        type:
          type: string
        balance:
          type: number
        category:
          type: string
        merchant:
          type: object
          properties:
            name:
              type: string
            category:
              type: string
            location:
              type: string
        notes:
          type: string
        attachments:
          type: array
          items:
            type: string
            format: uri
      required:
        - id
        - date
        - description
        - amount
        - type
        - balance
    Pagination:
      type: object
      properties:
        totalItems:
          type: integer
        totalPages:
          type: integer
        currentPage:
          type: integer