openapi: 3.0.0
info:
  title: Fraud Detection API
  description: API for detecting fraud risks and providing risk assessments for banking sessions and money movement transactions.
  version: 1.0.0
paths:
  /assess-session-risk:
    post:
      summary: Assess Session Risk
      description: Evaluates the risk level of a banking session based on user behavior and context
      operationId: assessSessionRisk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRiskAssessmentRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionRiskAssessmentResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /assess-transaction-risk:
    post:
      summary: Assess Transaction Risk
      description: Evaluates the risk level of a money movement transaction
      operationId: assessTransactionRisk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRiskAssessmentRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionRiskAssessmentResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    SessionRiskAssessmentRequest:
      type: object
      properties:
        sessionId:
          type: string
        userId:
          type: string
        deviceInfo:
          type: object
        ipAddress:
          type: string
        timestamp:
          type: string
      required:
        - sessionId
        - userId
    SessionRiskAssessmentResponse:
      type: object
      properties:
        riskLevel:
          type: string
          enum: [low, medium, high]
        riskScore:
          type: number
        factors:
          type: array
          items:
            type: string
      required:
        - riskLevel
        - riskScore
    TransactionRiskAssessmentRequest:
      type: object
      properties:
        transactionId:
          type: string
        amount:
          type: number
        sourceAccount:
          type: string
        destinationAccount:
          type: string
        timestamp:
          type: string
      required:
        - transactionId
        - amount
    TransactionRiskAssessmentResponse:
      type: object
      properties:
        riskLevel:
          type: string
          enum: [low, medium, high]
        riskScore:
          type: number
        recommendedAction:
          type: string
          enum: [approve, review, reject]
      required:
        - riskLevel
        - riskScore
        - recommendedAction