openapi: 3.0.0
info:
  title: Money Transfer API
  description: API for secure transfer of funds between accounts, supporting both internal transfers between own accounts and external transfers to other bank accounts.
  version: 1.0.0
paths:
  /internal-transfer:
    post:
      summary: Transfer Between Own Accounts
      description: Transfer money between accounts owned by the same user
      operationId: internalTransfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalTransferRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /external-transfer:
    post:
      summary: Transfer to External Account
      description: Transfer money to accounts at other banks
      operationId: externalTransfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalTransferRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalTransferResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    InternalTransferRequest:
      type: object
      properties:
        fromAccountId:
          type: string
        toAccountId:
          type: string
        amount:
          type: number
          minimum: 0
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
        description:
          type: string
          maxLength: 100
      required:
        - fromAccountId
        - toAccountId
        - amount
        - currency
    ExternalTransferRequest:
      type: object
      properties:
        fromAccountId:
          type: string
        recipientName:
          type: string
        recipientBank:
          type: string
        recipientAccountNumber:
          type: string
        amount:
          type: number
          minimum: 0
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
        description:
          type: string
          maxLength: 100
      required:
        - fromAccountId
        - recipientName
        - recipientBank
        - recipientAccountNumber
        - amount
        - currency
    TransferResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
          enum: [completed, pending, failed]
        timestamp:
          type: string
          format: date-time
      required:
        - transactionId
        - status
        - timestamp
    ExternalTransferResponse:
      type: object
      properties:
        transactionId:
          type: string
        status:
          type: string
          enum: [completed, pending, failed]
        estimatedCompletionTime:
          type: string
          format: date-time
        fees:
          type: number
      required:
        - transactionId
        - status
        - estimatedCompletionTime